/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientViews;
import java.util.List;
import clientViews.UserAmiView;
import controllers.ClientController;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author wadem
 */
public class amisPage extends javax.swing.JFrame {

    /**
     * Creates new form amisPage
     * 
     * 
     */
    private static amisPage instance;
    private static String utilisateurCurrent;
    private mainPage mainPageInstance;
    ClientController clientController;
    String reponse;
    
    private Timer updateTimer;
    
    public amisPage(String utilisateur){
        initComponents();
        utilisateurCurrent=utilisateur;
        instance=this;
        reponse="";
        listerAmies(utilisateur);
        userLogin.setText(utilisateur);
        
         actualizerListAmis();
        try{
        this.mainPageInstance=mainPage.getInstance();
        }catch(Exception e){
            
        }
    }
      public static amisPage getInstance() throws Exception{
          if (instance == null) {
            instance = new amisPage(utilisateurCurrent);
        }
          return instance;
     }
      public String getUtilisateurCurrent() {
          return utilisateurCurrent;
     }
      
     private void listerAmies(String utilisateur) {
         try{
           clientController=new ClientController();
           reponse=clientController.listerAmis(utilisateur);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){
                    int size=requete.length;
                     if(size>3){
                        //AucunAmiLabel.setVisible(false);
                        String [] listAmis=requete[3].split("\n");
                        for (String ami : listAmis) {
                                UserAmiView panneauAmi = new UserAmiView(ami);
                                lisUsersPanel.add(panneauAmi);
                                lisUsersPanel.add(Box.createRigidArea(new Dimension(0, 5)));
                           }
                     }else{
                         //AucunAmiLabel.setVisible(true);
                         //AucunAmiLabel.setText("Vous avez pas encore des amis");
                     }
                     
                   
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
         }catch(Exception e){
              System.out.println("Exception Lister Amis" + e.getMessage());
         }
           // Espace entre les amis
      }
     
     
      private void logOut(String utilisateur) {
         try{
           clientController=new ClientController();
           reponse=clientController.deconnecter(utilisateur);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){
                    String [] listAmis=requete[3].split(",");
                    JOptionPane.showMessageDialog(this, "Deconnexion validé:"+requete[3], "Logout", JOptionPane.INFORMATION_MESSAGE);
                   
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
         }catch(Exception e){
              System.out.println("Exception LogOut" + e.getMessage());
         }
           // Espace entre les amis
      }
     
     public void actualizerListAmis() {
        lisUsersPanel.removeAll(); // Limpa os elementos existentes no painel
        listerAmies(utilisateurCurrent); // Recarrega as mensagens
        lisUsersPanel.revalidate(); // Atualiza a interface gráfica
        lisUsersPanel.repaint(); // Re-renderiza o painel
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        amiLabel = new javax.swing.JLabel();
        invitationButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userLogin = new javax.swing.JLabel();
        retourButton = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lisUsersPanel = new javax.swing.JPanel();
        AucunAmiLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        amiLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        amiLabel.setText("Liste des Amis");

        invitationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/following.png"))); // NOI18N
        invitationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invitationButtonActionPerformed(evt);
            }
        });

        addUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user-add.png"))); // NOI18N
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-logout-26.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("logo");

        userLogin.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        userLogin.setText("Anete");

        retourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-return-32.png"))); // NOI18N
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        Refresh.setText("Refraichir");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lisUsersPanel.setBackground(new java.awt.Color(255, 255, 255));
        lisUsersPanel.setLayout(new javax.swing.BoxLayout(lisUsersPanel, javax.swing.BoxLayout.Y_AXIS));

        AucunAmiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lisUsersPanel.add(AucunAmiLabel);

        jScrollPane3.setViewportView(lisUsersPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(Refresh)
                        .addGap(18, 18, 18)
                        .addComponent(invitationButton)
                        .addGap(18, 18, 18)
                        .addComponent(addUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invitationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userLogin))
                            .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(amiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invitationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invitationButtonActionPerformed
        // TODO add your handling code here:
      new invitationPage().setVisible(true);
      this.dispose(); // Fermer la fenêtre actuelle si nécessaire  
    }//GEN-LAST:event_invitationButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
        new demandePage().setVisible(true);
        this.dispose(); // Fermer la fenêtre actuelle si nécessaire 
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new accueilAPP().setVisible(true);
        this.dispose(); // Fermer la fenêtre actuelle si nécessaire 
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        // TODO add your handling code here:
        /*amisPage retour = new amisPage ();
        retour.setVisible(true);*/
        mainPageInstance.setVisible(true);
        this.dispose(); // Ferme la page actuelle si tu veux
    }//GEN-LAST:event_retourButtonActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
       actualizerListAmis();
    }//GEN-LAST:event_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amisPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amisPage(utilisateurCurrent).setVisible(true);
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AucunAmiLabel;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton addUserButton;
    private javax.swing.JLabel amiLabel;
    private javax.swing.JButton invitationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel lisUsersPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton retourButton;
    private javax.swing.JLabel userLogin;
    // End of variables declaration//GEN-END:variables
}
