/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientViews;

import controllers.ClientController;
import java.awt.Dimension;
import java.util.List;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author wadem
 */
public class demandePage extends javax.swing.JFrame {

    /**
     * Creates new form demandePage
     */
    private amisPage pageAccueilInstance;
    private static String currentUser;
    private UserFaireDemandeView panneauUtilisateur;
    ClientController clientController;
    String reponse;
    public demandePage() {
        initComponents();
        try{
             this.pageAccueilInstance= amisPage.getInstance();
             currentUser=pageAccueilInstance.getUtilisateurCurrent();
             clientController=new ClientController();
             listerUtilisateurs(currentUser,clientController);
             userLogin1.setText(currentUser);
        }catch(Exception e){
            
        }
    }
    
        private void listerUtilisateurs(String utilisateur, ClientController clientController) {
         try{
           reponse=clientController.listerSuggestions(utilisateur);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){
                    int size=requete.length;
                    if(size>3){
                     String [] listSuggestions=requete[3].split("\n");
                     JOptionPane.showMessageDialog(this, "Suggestions:"+requete[3], "Login", JOptionPane.INFORMATION_MESSAGE);
                     for (String user : listSuggestions) {
                           UserFaireDemandeView panneauUtilisateur = new UserFaireDemandeView(user);
                            listUsersPanel.add(panneauUtilisateur);
                            
                            listUsersPanel.add(Box.createRigidArea(new Dimension(0, 5)));
                        }
                    }
                   
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
         }catch(Exception e){
              System.out.println("Exception Lister Amis" + e.getMessage());
         }
           // Espace entre les amis
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mesdemandeButton = new javax.swing.JButton();
        retourButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsersPanel = new javax.swing.JPanel();
        userLogin1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        userLogin.setText("Anete");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userIcon.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mesdemandeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-trust-30.png"))); // NOI18N
        mesdemandeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesdemandeButtonActionPerformed(evt);
            }
        });

        retourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-return-32.png"))); // NOI18N
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Logo");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Suggestion d'amis ");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listUsersPanel.setBackground(new java.awt.Color(255, 255, 255));
        listUsersPanel.setLayout(new javax.swing.BoxLayout(listUsersPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(listUsersPanel);

        userLogin1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        userLogin1.setText("xxxx");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesdemandeButton)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(mesdemandeButton)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addContainerGap(340, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(userLogin1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(135, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        // TODO add your handling code here:
       pageAccueilInstance.setVisible(true);
       pageAccueilInstance.actualizerListAmis();
        this.dispose(); // Fermer la fenêtre actuelle si nécessaire 
    }//GEN-LAST:event_retourButtonActionPerformed

    private void mesdemandeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesdemandeButtonActionPerformed
        // TODO add your handling code here:
        new mesdemandesPage().setVisible(true);
this.dispose(); // Fermer la fenêtre actuelle si nécessaire 
    }//GEN-LAST:event_mesdemandeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demandePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demandePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demandePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demandePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demandePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listUsersPanel;
    private javax.swing.JButton mesdemandeButton;
    private javax.swing.JButton retourButton;
    private javax.swing.JLabel userLogin;
    private javax.swing.JLabel userLogin1;
    // End of variables declaration//GEN-END:variables
}
