/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package clientViews;

import controllers.ClientController;
import java.awt.Dimension;
import java.util.List;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author wadem
 */
public class invitationPage extends javax.swing.JFrame {

    /** Creates new form invitationPage */
    private amisPage pageAccueilInstance;
    private static String currentUser;
    ClientController clientController;
    String reponse;
    public invitationPage() {
        initComponents();
        try{
            this.pageAccueilInstance= amisPage.getInstance();
            currentUser=pageAccueilInstance.getUtilisateurCurrent();
            clientController=new ClientController();
            listerDemandeAmis(currentUser);
            userLogin.setText(currentUser);
        }catch(Exception e){
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AucunAmiLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        invitationLabel = new javax.swing.JLabel();
        retourButton = new javax.swing.JButton();
        userLogin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDemandePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(435, 430));

        AucunAmiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        logoLabel.setText("Logo");

        invitationLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        invitationLabel.setText("Invitations Reçus ");

        retourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-return-32.png"))); // NOI18N
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        userLogin.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        userLogin.setText("xxxx");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userIcon.png"))); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listDemandePanel.setBackground(new java.awt.Color(255, 255, 255));
        listDemandePanel.setLayout(new javax.swing.BoxLayout(listDemandePanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(listDemandePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(invitationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AucunAmiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(retourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logoLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(invitationLabel)
                        .addGap(27, 27, 27)
                        .addComponent(AucunAmiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        // TODO add your handling code here:
        pageAccueilInstance.setVisible(true);
        pageAccueilInstance.actualizerListAmis();
        this.dispose(); // Fermer la fenêtre actuelle si nécessaire 
    }//GEN-LAST:event_retourButtonActionPerformed
      private void listerDemandeAmis(String utilisateur) {
         try{    
           reponse=clientController.listerDemandesAmis(utilisateur);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){   
                int size=requete.length;
                    if(size>3){
                     AucunAmiLabel.setVisible(false);
                    String [] listDemandeAmis=requete[3].split("\n");
                    JOptionPane.showMessageDialog(this, "liste de demandes "+requete[3], "Login", JOptionPane.INFORMATION_MESSAGE);
                    for (String demande : listDemandeAmis) {
                            UserDemandeRecuView panneauUtilisateur = new UserDemandeRecuView(demande);
                            listDemandePanel.add(panneauUtilisateur);
                            listDemandePanel.add(Box.createRigidArea(new Dimension(0, 5)));
                        }
                    }else{
                         AucunAmiLabel.setVisible(true);
                         AucunAmiLabel.setText("Vous n'avez pas de demande");
                     }
                   
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
         }catch(Exception e){
              System.out.println("Exception Lister Amis" + e.getMessage());
         }
           // Espace entre les amis
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invitationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invitationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invitationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invitationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new invitationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AucunAmiLabel;
    private javax.swing.JLabel invitationLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel listDemandePanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton retourButton;
    private javax.swing.JLabel userLogin;
    // End of variables declaration//GEN-END:variables

}
