/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientViews;

import controllers.ClientController;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author etena
 */
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form mainPage
     */
   
    private static mainPage instance;
    ClientController clientController;
    String reponse;
    private static String utilisateurCurrent;
    private Timer updateTimer;

    public mainPage(String utilisateur){
        initComponents();
        utilisateurCurrent=utilisateur;
        instance=this;
        reponse="";
       // listerMessages(utilisateur);
        userLogin.setText(utilisateur);
         try{clientController=new ClientController();}catch(Exception e){}
        
       updateTimer = new Timer(20000, e -> actualizerMessages());
       updateTimer.start();
    }
    
     public void actualizerMessages() {
        listUsersMessage.removeAll();
        listUsersMessage.revalidate(); // Atualiza a interface gráfica
        listerMessages(utilisateurCurrent);
        listUsersMessage.repaint(); // Re-renderiza o painel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JLabel();
        messageButton = new javax.swing.JButton();
        amisButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        MessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsersMessage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userIcon.png"))); // NOI18N

        userLogin.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N

        messageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-nouveau-message-48.png"))); // NOI18N
        messageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageButtonActionPerformed(evt);
            }
        });

        amisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-collaboration-48.png"))); // NOI18N
        amisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amisButtonActionPerformed(evt);
            }
        });

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-logout-26.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        MessageLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        MessageLabel.setText("Messages");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listUsersMessage.setBackground(new java.awt.Color(255, 255, 255));
        listUsersMessage.setLayout(new javax.swing.BoxLayout(listUsersMessage, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(listUsersMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(360, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amisButton)
                        .addGap(40, 40, 40)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(userLogin))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amisButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageButtonActionPerformed
           new chatPage().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_messageButtonActionPerformed

    private void amisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amisButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
       // amisPage accueil= new amisPage(utilisateurCurrent);
       //accueil.setVisible(true);
       //new pageAccueil(utilisateurCurrent).setVisible(true);
       new amisPage(utilisateurCurrent).setVisible(true);
        
        this.dispose();
        //this.dispose();
    }//GEN-LAST:event_amisButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        // Fermer la fenêtre actuelle si nécessaire
        try{
            clientController.deconnecter(utilisateurCurrent);
            clientController.fermer();
            new accueilAPP().setVisible(true);
            this.dispose();
        }catch(Exception e){}
    }//GEN-LAST:event_logoutButtonActionPerformed

      public static mainPage getInstance() throws Exception{
          if (instance == null) {
            instance = new mainPage(utilisateurCurrent);
            }
            return instance;
     }
      public String getUtilisateurCurrent() {
          return utilisateurCurrent;
     }
    private void listerMessages(String utilisateur) {
         try{
           reponse=clientController.lectureMessage(utilisateur);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){
                    int size=requete.length;
                     if(size>3){
                        //AucunMessageLabel.setVisible(false);
                        String [] listMessage=requete[3].split("\n");
                        for (String message : listMessage) {
                                UserMessageView panneauMessage = new UserMessageView (message);
                                listUsersMessage.add(panneauMessage);
                                listUsersMessage.add(Box.createRigidArea(new Dimension(0, 5)));
                            }
                     }else{
                         //AucunMessageLabel.setVisible(true);
                         //AucunMessageLabel.setText("Vous n'avez pas encore des messages");
                     }
                                      
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
         }catch(Exception e){
              System.out.println("Exception Lister Messages:" + e.getMessage());
         }
           // Espace entre les amis
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage(utilisateurCurrent).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JButton amisButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listUsersMessage;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton messageButton;
    private javax.swing.JLabel userLogin;
    // End of variables declaration//GEN-END:variables
}
