/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clientViews;

import controllers.ClientController;
import javax.swing.JOptionPane;

/**
 *
 * @author etena
 */
public class UserDemandeRecuView extends javax.swing.JPanel {

    /**
     * Creates new form UserDemandeRecuView
     */
 
    String utilisateurAmi,currentUtilisateur;
    ClientController clientController;
    
    private amisPage pageAccueilInstance;
    String reponse;
    public UserDemandeRecuView(String user) {
        initComponents();
         try{
            utilisateurAmi=user;
            this.pageAccueilInstance= amisPage.getInstance();
            currentUtilisateur=pageAccueilInstance.getUtilisateurCurrent(); 
            userName.setText(user);
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIcon = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        refuserButton = new javax.swing.JButton();
        accepterButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(132, 124, 220)));
        setMaximumSize(new java.awt.Dimension(404, 48));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userIcon.png"))); // NOI18N

        userName.setText("Kushina Uzumaki");

        refuserButton.setText("Refuser");
        refuserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refuserButtonActionPerformed(evt);
            }
        });

        accepterButton.setText("Accepter");
        accepterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accepterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refuserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userName)
                            .addComponent(refuserButton)
                            .addComponent(accepterButton))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refuserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refuserButtonActionPerformed
        // TODO add your handling code here:

        //ENVOYER LA DEMANDE D'AMITIE AU UTILISATEUR
          try{
           clientController=new ClientController();
           reponse=clientController.reponseDemande(currentUtilisateur,"refuser",utilisateurAmi);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){
                 
                        JOptionPane.showMessageDialog(this, "Demande Refusé :"+requete[3], "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
       }catch(Exception e){
           
       }
    }//GEN-LAST:event_refuserButtonActionPerformed

    private void accepterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepterButtonActionPerformed
        // TODO add your handling code here:
           try{
           clientController=new ClientController();
           reponse=clientController.reponseDemande(currentUtilisateur,"accepter",utilisateurAmi);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){
                        JOptionPane.showMessageDialog(this, "Demande Accepté :"+requete[3], "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
       }catch(Exception e){
           
       }
        
    }//GEN-LAST:event_accepterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepterButton;
    private javax.swing.JButton refuserButton;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
