/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clientViews;

import controllers.ClientController;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author etena
 */
public class UserFaireDemandeView extends javax.swing.JPanel {

    /**
     * Creates new form UserDemandeView
     */
    String utilisateur,currentUser;
    ClientController clientController;
    String reponse;
    
    private amisPage pageAccueilInstance;
    public UserFaireDemandeView(String user) {
        initComponents();
         try{
            utilisateur=user;
            this.pageAccueilInstance= amisPage.getInstance();
            currentUser=pageAccueilInstance.getUtilisateurCurrent(); 
            userName.setText(user);
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName = new javax.swing.JLabel();
        ajouterButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        userName.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        userName.setText("Kushina Uzumaki");

        ajouterButton.setText("Ajouter");
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(ajouterButton)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterButton)
                    .addComponent(userName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        // TODO add your handling code here:
                    
       try{
           clientController=new ClientController();
           reponse=clientController.demanderAmi(currentUser,utilisateur);
             String[] requete = reponse.split(",");
                if(requete[2].equals("succes")){
                 
                        JOptionPane.showMessageDialog(this, "Demande Envoye :"+requete[3], "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, requete[3], "Erreur", JOptionPane.ERROR_MESSAGE);
                }
       }catch(Exception e){
           
       }
        
        //ENVOYER LA DEMANDE D'AMITIE AU UTILISATEUR
    }//GEN-LAST:event_ajouterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
